name: CI Frontend Angular

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  frontend:
    runs-on: ubuntu-latest

    steps:

      - name: Obtener código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test -- --watch=false

      - name: Construir Angular
        run: npm run build